      SUBROUTINE GENABCD(LIMX, MULT, O, IO, ABCD, A, B, C, D)
      IMPLICIT NONE
      INTEGER LIMX
      DOUBLE COMPLEX UNITY, ZERO
      DOUBLE COMPLEX A(LIMX, LIMX), B(LIMX, LIMX),
     +               C(LIMX, LIMX), D(LIMX, LIMX)
      DOUBLE COMPLEX MULT(2*LIMX, 2*LIMX),
     +               O(2*LIMX, 2*LIMX), IO(2*LIMX, 2*LIMX),
     +               TEMP(2*LIMX, 2*LIMX),
     + ABCD(2*LIMX, 2*LIMX)

      UNITY = 1.0
      ZERO = 0.0

C$$$ ZGEMM MULTIPLIES MATRICES TOGETHER

         CALL ZGEMM('N', 'N', 2*LIMX, 2*LIMX, 2*LIMX, UNITY, MULT,
     +         2*LIMX, O, 2*LIMX, ZERO, TEMP, 2*LIMX)
         CALL ZGEMM('N', 'N', 2*LIMX, 2*LIMX, 2*LIMX, UNITY, IO,
     +         2*LIMX, TEMP, 2*LIMX, ZERO, ABCD, 2*LIMX)

c$$$  To be removed for block matrices
         A=ABCD(1:LIMX, 1:LIMX)
         B=ABCD((LIMX+1):2*LIMX, 1:LIMX)
         C=ABCD(1:LIMX, LIMX+1:2*LIMX)
         D=ABCD((LIMX+1):2*LIMX, (LIMX+1):2*LIMX)

C$$$ I HAVE VERIFIED THAT AD-BC=1 (IDENTITY MATRIX) AS EXPECTED
      RETURN
      END
C$$$ ROUTINE TO GENERATE T AND R
      SUBROUTINE GENTANDRINC(LIMX, TINC,RINC,TTILDEINC,RTILDEINC,A,B,
     + C,D)
      IMPLICIT NONE
      INTEGER LIMX
      DOUBLE COMPLEX UNITY, ZERO
      DOUBLE COMPLEX A(LIMX, LIMX), B(LIMX, LIMX),
     +               C(LIMX, LIMX), D(LIMX, LIMX),
     + TINC(LIMX, LIMX), TTILDEINC(LIMX, LIMX),
     + RINC(LIMX, LIMX), RTILDEINC(LIMX, LIMX)
c     UNITMATRIX is no longer needed
c     UNITMATRIX(LIMX, LIMX)

      UNITY = 1.0
      ZERO = 0.0
c     Not needed
c     CALL ZLASET ('ALL', LIMX, LIMX, ZERO, ONE, UNITMATRIX, LIMX)
C$$$ T~ = D^-1
      CALL ZCOPY(LIMX*LIMX, D, 1, TTILDEINC, 1)
      CALL INVERTMATRIX(TTILDEINC, LIMX)
C$$$ R~ = BD^-1
      CALL ZGEMM('N', 'N', LIMX, LIMX, LIMX, UNITY, B,
     +      LIMX, TTILDEINC, LIMX, ZERO, RTILDEINC, LIMX)
C$$$ R = -D^-1 C
      CALL ZGEMM('N', 'N', LIMX, LIMX, LIMX, -1*UNITY, TTILDEINC,
     +      LIMX, C, LIMX, ZERO, RINC, LIMX)
C$$$ R=-R
C$$$ T=(A-)? BD^-1 C
C$$$ Thus, We can simply reuse R here: T = A + B * R
C$$$ Also, removed a slow call to zgemm, replacing it with zcopy
      CALL ZCOPY(LIMX*LIMX, A, 1, TINC, 1)
      CALL ZGEMM('N', 'N', LIMX, LIMX, LIMX, UNITY, B,
     +      LIMX, RINC, LIMX, UNITY, TINC, LIMX)

      RETURN
      END

      SUBROUTINE UPDATETANDR(TINC, TTILDEINC, R, RTILDEINC, T, TTILDE,
     + RTILDE, LIMX, RINC)
      IMPLICIT NONE
      INTEGER LIMX
      DOUBLE COMPLEX T(LIMX, LIMX), TTILDE(LIMX, LIMX),
     +               R(LIMX, LIMX), RTILDE(LIMX, LIMX),
     +               TINC(LIMX, LIMX), TTILDEINC(LIMX, LIMX),
     + RINC(LIMX, LIMX), RTILDEINC(LIMX, LIMX)

C$$$ TEMPORARY LOCAL VARIABLES
      DOUBLE COMPLEX T1TEMP(LIMX, LIMX), TTILDE1TEMP(LIMX, LIMX),
     +               R1TEMP(LIMX, LIMX), RTILDE1TEMP(LIMX, LIMX)
      DOUBLE COMPLEX UNITY, ZERO
      DOUBLE COMPLEX BRACKET12(LIMX, LIMX), BRACKET21(LIMX, LIMX),
     +               TRTEMP(LIMX, LIMX), TRTEMP2(LIMX, LIMX),
     + UNITMATRIX(LIMX, LIMX), ALLZERO(LIMX, LIMX)
      UNITY = 1.0
      ZERO = 0.0
      CALL ZCOPY(LIMX*LIMX, T, 1, T1TEMP, 1)
      CALL ZCOPY(LIMX*LIMX, TTILDE, 1, TTILDE1TEMP, 1)
      CALL ZCOPY(LIMX*LIMX, R, 1, R1TEMP, 1)
      CALL ZCOPY(LIMX*LIMX, RTILDE, 1, RTILDE1TEMP, 1)
      CALL ZLASET ('ALL', LIMX, LIMX, ZERO, ZERO,  ALLZERO, LIMX)
      CALL ZLASET ('ALL', LIMX, LIMX, ZERO, UNITY, UNITMATRIX, LIMX)

C$$$ BRACKET12 = (1 - RTILDE1.R2)^-1
      CALL ZCOPY (LIMX*LIMX, UNITMATRIX, 1, BRACKET12, 1)
      CALL ZGEMM('N', 'N', LIMX, LIMX, LIMX, -UNITY, RTILDE1TEMP, LIMX,
     + RINC, LIMX, UNITY, BRACKET12, LIMX)
      CALL INVERTMATRIX(BRACKET12, LIMX)

C$$$ BRACKET21 = (1 - R2.RTILDE1)^-1
      CALL ZCOPY (LIMX*LIMX, UNITMATRIX, 1, BRACKET21, 1)
      CALL ZGEMM('N', 'N', LIMX, LIMX, LIMX, -UNITY, RINC, LIMX,
     + RTILDE1TEMP, LIMX, UNITY, BRACKET21, LIMX)
      CALL INVERTMATRIX(BRACKET21, LIMX)


C$$$ T = T2.BRACKET12.T1
C$$$ Note: T2*Br12 can be reused later.
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TINC, LIMX,
     +  BRACKET12, LIMX, ZERO, TRTEMP, LIMX)
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP, LIMX,
     +  T1TEMP, LIMX, ZERO, T, LIMX)

C$$$ RTILDE = RTILDE2 + T2.BRACKET12.RTILDE1.TTILDE2
      CALL ZCOPY (LIMX*LIMX, RTILDEINC, 1, RTILDE, 1)
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP, LIMX,
     +  RTILDE1TEMP, LIMX, ZERO, TRTEMP2, LIMX)

      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP2, LIMX,
     +  TTILDEINC, LIMX, UNITY, RTILDE, LIMX)

C$$$ TTILDE = TTILDE1.BRACKET21.TTILDE2
C$$$ Note: T1~ * Br21 can be reused later. I reorganized the code
C$$$ to make it possible
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TTILDE1TEMP,
     +  LIMX, BRACKET21, LIMX, ZERO, TRTEMP, LIMX)
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP,
     +  LIMX, TTILDEINC, LIMX, ZERO, TTILDE, LIMX)

C$$$ R = R1 + TTILDE1.BRACKET21.R2.T1. Note: TRTEMP from above is reused here
      CALL ZCOPY (LIMX*LIMX, R1TEMP, 1, R, 1)
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP, LIMX,
     +  RINC, LIMX, ZERO, TRTEMP2, LIMX)
      CALL ZGEMM ('N', 'N', LIMX, LIMX, LIMX, UNITY, TRTEMP2, LIMX,
     +  T1TEMP, LIMX, UNITY, R, LIMX)
      RETURN
      END
