c$$   NEW SUBROUTINE TO GENERATE A,B,C,D
      SUBROUTINE GENABCDNEW(LIMX, MULT, A, B, C, D,U)
      IMPLICIT NONE
      INTEGER LIMX
      DOUBLE COMPLEX UNITY, ZERO,NEG,HALF,NHALF, ZI/(0.0, 1.0)/
      DOUBLE COMPLEX A(LIMX, LIMX), B(LIMX, LIMX),
     +               C(LIMX, LIMX), D(LIMX, LIMX)
      DOUBLE COMPLEX MULT(2*LIMX, 2*LIMX),
     +               O(2*LIMX, 2*LIMX), IO(2*LIMX, 2*LIMX),
     +               TEMP(2*LIMX, 2*LIMX),
     + ABCD(2*LIMX, 2*LIMX),
C    M(A,B,C,D) COMPONENTS OF MATRIX, U: PHASE MATRIX
     + MA(LIMX,LIMX),MB(LIMX,LIMX),MC(LIMX,LIMX),MD(lIMX,LIMX),
     + U(LIMX,LIMX),TEMPX(LIMX,LIMX),TEMPY(LIMX,LIMX),
     + LAMONE(LIMX,LIMX),LAMTWO(LIMX,LIMX)
     
      UNITY = 1.0
      ZERO  = 0.0
      NEG   =-1.0
      HALF  = 0.5
      NHALF = -0.5

C     
      MA = MULT(1:LIMX, 1:LIMX)
      MB = MULT((LIMX+1):2*LIMX, 1:LIMX)
      MC = MULT(1:LIMX, LIMX+1:2*LIMX)
      MD = MULT((LIMX+1):2*LIMX, (LIMX+1):2*LIMX)

c     OLD INTITISE
c      MA = MULT(1:LIMX, 1:LIMX)
c      MB = MULT((LIMX+1):2*LIMX, 1:LIMX)
c      MC = MULT(1:LIMX, LIMX+1:2*LIMX)
c      MD = MULT((LIMX+1):2*LIMX, (LIMX+1):2*LIMX)

c$$$ M(A,B,C,D) INITALISE TO ZERO'S
      CALL SQZERO(A,LIMX)
      CALL SQZERO(B,LIMX)
      CALL SQZERO(C,LIMX)
      CALL SQZERO(D,LIMX)
      CALL SQUNITZ(U, ZI, LIMX)

c      call zprintm (U, LIMX, 'u: ')
c     CALL SQDOT (TEMP, MULT, O,  2*LIMX)
c     CALL SQDOT (ABCD, IO, TEMP, 2*LIMX)

      CALL SQDOT(TEMPX,MB,U,LIMX)
      CALL SQDOT(LAMONE,MD,U,LIMX)

      CALL ZGEMM('C','N',LIMX,LIMX,LIMX,UNITY,U,LIMX,MC,LIMX,UNITY,
     + TEMPY,LIMX)
      CALL ZGEMM('C','N',LIMX,LIMX,LIMX,UNITY,U,LIMX,LAMONE,LIMX,UNITY,
     + LAMTWO,LIMX)

c$$$ CREATED TEMP MATICIES -> GENERATE A
      CALL ZAXPY(LIMX*LIMX,HALF,MA,1,A,1)
      CALL ZAXPY(LIMX*LIMX,HALF,TEMPX,1,A,1)
      CALL ZAXPY(LIMX*LIMX,HALF,TEMPY,1,A,1)
      CALL ZAXPY(LIMX*LIMX,HALF,LAMTWO,1,A,1)
c$$$ GENERATE B
      CALL ZAXPY(LIMX*LIMX,HALF,MA,1,B,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,TEMPX,1,B,1)
      CALL ZAXPY(LIMX*LIMX,HALF,TEMPY,1,B,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,LAMTWO,1,B,1)
c$$$  GENERTATE C
      CALL ZAXPY(LIMX*LIMX,HALF,MA,1,C,1)
      CALL ZAXPY(LIMX*LIMX,HALF,TEMPX,1,C,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,TEMPY,1,C,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,LAMTWO,1,C,1)      
c$$$  GENERTATE D
      CALL ZAXPY(LIMX*LIMX,HALF,MA,1,D,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,TEMPX,1,D,1)
      CALL ZAXPY(LIMX*LIMX,NHALF,TEMPY,1,D,1)
      CALL ZAXPY(LIMX*LIMX,HALF,LAMTWO,1,D,1)      


C$$$ I HAVE VERIFIED THAT AD-BC=1 (IDENTITY MATRIX) AS EXPECTED
      RETURN
      END
 
